<%@ Page Language="C#" AutoEventWireup="true" CodeFile="UpdateWithStoredProcedure.aspx.cs" Inherits="UpdateWithStoredProcedure" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
        ProviderName="System.Data.SqlClient" ConnectionString="<%$ ConnectionStrings: nashNorthwind %>" DataSourceMode="DataSet" 
        SelectCommand="GetAllEmployees" SelectCommandType="StoredProcedure"
        UpdateCommand="UpdateEmployee" UpdateCommandType="StoredProcedure"
        DeleteCommand="Delete Employees where EmployeeID=@EmployeeID" ConflictDetection="OverwriteChanges">             
        </asp:SqlDataSource>

        <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="EmployeeID">
        </asp:GridView>
    </div>
    </form>
</body>
</html>
